#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
PRESET_ROOT = ROOT / "backend/src/main/resources/practice/preset"
MANIFEST = PRESET_ROOT / "manifest.json"
TARGET = ROOT / "entry/src/main/ets/data/practice/PresetPracticeCatalog.ets"

GRADE_ORDER = {f"G{i}": i for i in range(1, 7)}
SUBJECT_ORDER = {"CHINESE": 0, "MATH": 1, "ENGLISH": 2}
LEGACY_KIND_ORDER = {"STARTER": 0, "CORE": 1}


def q(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def enum(prefix: str, value: str) -> str:
    return f"{prefix}.{value}"


def load_papers() -> list[dict]:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    papers: list[dict] = []
    for relative in manifest["files"]:
        shard = json.loads((PRESET_ROOT / relative).read_text(encoding="utf-8"))
        papers.extend(shard["papers"])
    return papers


def legacy_sort_key(paper: dict) -> tuple:
    parts = paper["id"].split("-")
    kind = "STARTER" if "-STARTER-" in paper["id"] else "CORE"
    return (
        GRADE_ORDER[paper["grade"]],
        LEGACY_KIND_ORDER.get(kind, 9),
        SUBJECT_ORDER[paper["subject"]],
        paper["id"],
    )


def semester_sort_key(paper: dict) -> tuple:
    return (
        GRADE_ORDER[paper["grade"]],
        SUBJECT_ORDER[paper["subject"]],
        paper["id"],
    )


def ordered_papers(papers: list[dict]) -> list[dict]:
    legacy = sorted((p for p in papers if p["semester"] == "ALL"), key=legacy_sort_key)
    semester = sorted(
        (p for p in papers if p["semester"] != "ALL" and "-P0-" not in p["id"]),
        key=semester_sort_key,
    )
    visual_p0 = sorted(
        (p for p in papers if p["semester"] != "ALL" and "-P0-" in p["id"]),
        key=semester_sort_key,
    )
    return legacy + semester + visual_p0


def render(papers: list[dict]) -> str:
    lines = [
        "// GENERATED from backend/src/main/resources/practice/preset/manifest.json and grade/subject shards.",
        "// Run: python scripts/generate_practice_catalog.py",
        "// Do not edit this file by hand.",
        "import {",
        "  PracticeDifficulty,",
        "  PracticeGrade,",
        "  PracticePaper,",
        "  PracticePaperStatus,",
        "  PracticeSemester,",
        "  PracticeSourceType,",
        "  PracticeSubject",
        "} from '../../domain/model/practice/PracticeModels';",
        "",
        "export class PresetPracticeCatalog {",
        "  static papers(): PracticePaper[] {",
        "    let result: PracticePaper[] = [];",
    ]
    for paper in ordered_papers(papers):
        tags = ", ".join(q(tag) for tag in paper["tags"])
        lines.extend([
            "    result.push({",
            f"      id: {q(paper['id'])},",
            f"      version: {paper['version']},",
            f"      grade: {enum('PracticeGrade', paper['grade'])},",
            f"      subject: {enum('PracticeSubject', paper['subject'])},",
            f"      semester: {enum('PracticeSemester', paper['semester'])},",
            f"      title: {q(paper['title'])},",
            f"      description: {q(paper['description'])},",
            f"      difficulty: {enum('PracticeDifficulty', paper['difficulty'])},",
            f"      questionCount: {paper['questionCount']},",
            f"      estimatedMinutes: {paper['estimatedMinutes']},",
            f"      tags: [{tags}],",
            f"      sourceType: {enum('PracticeSourceType', paper['sourceType'])},",
            f"      status: {enum('PracticePaperStatus', paper['status'])}",
            "    });",
        ])
    lines.extend(["    return result;", "  }", "}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render(load_papers())
    if args.check:
        actual = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if actual != expected:
            print("PRACTICE_CATALOG_GENERATED_FILE_OUT_OF_DATE", file=sys.stderr)
            print("Run: python scripts/generate_practice_catalog.py", file=sys.stderr)
            return 1
        print("PRACTICE_CATALOG_GENERATED_FILE_OK")
        return 0
    TARGET.write_text(expected, encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(ROOT)} from split preset catalog")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
