#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "backend/src/main/resources/practice/preset-catalog.json"
TARGET = ROOT / "entry/src/main/ets/data/practice/PresetPracticeCatalog.ets"


def q(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def enum(prefix: str, value: str) -> str:
    return f"{prefix}.{value}"


def render(catalog: dict) -> str:
    lines = [
        "// GENERATED from backend/src/main/resources/practice/preset-catalog.json.",
        "// Run: python scripts/generate_practice_catalog.py",
        "// Do not edit this file by hand.",
        "import {",
        "  PracticeDifficulty,",
        "  PracticeGrade,",
        "  PracticePaper,",
        "  PracticePaperStatus,",
        "  PracticeSourceType,",
        "  PracticeSubject",
        "} from '../../domain/model/practice/PracticeModels';",
        "",
        "export class PresetPracticeCatalog {",
        "  static papers(): PracticePaper[] {",
        "    let result: PracticePaper[] = [];",
    ]
    for paper in catalog["papers"]:
        tags = ", ".join(q(tag) for tag in paper["tags"])
        lines.extend([
            "    result.push({",
            f"      id: {q(paper['id'])},",
            f"      version: {paper['version']},",
            f"      grade: {enum('PracticeGrade', paper['grade'])},",
            f"      subject: {enum('PracticeSubject', paper['subject'])},",
            f"      title: {q(paper['title'])},",
            f"      description: {q(paper['description'])},",
            f"      difficulty: {enum('PracticeDifficulty', paper['difficulty'])},",
            f"      questionCount: {paper['questionCount']},",
            f"      estimatedMinutes: {paper['estimatedMinutes']},",
            f"      tags: [{tags}],",
            f"      sourceType: {enum('PracticeSourceType', paper['sourceType'])},",
            f"      status: {enum('PracticePaperStatus', paper['status'])}",
            "    });",
        ])
    lines.extend([
        "    return result;",
        "  }",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    expected = render(catalog)
    if args.check:
        actual = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if actual != expected:
            print("PRACTICE_CATALOG_GENERATED_FILE_OUT_OF_DATE", file=sys.stderr)
            print("Run: python scripts/generate_practice_catalog.py", file=sys.stderr)
            return 1
        print("PRACTICE_CATALOG_GENERATED_FILE_OK")
        return 0
    TARGET.write_text(expected, encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(ROOT)} from {CATALOG.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
